### ISSUE TITLE
Change config-alias

### ISSUE THREAD

**Issue by innoflash** [fwartner/laravel-tinkerwell-snippets#1]
https://github.com/fwartner/laravel-tinkerwell-snippets/blob/ba031b9b8e7d47b18dcfdb928a890f97e307fa6f/src/TinkerwellSnippetsServiceProvider.php#L25

Given when developing Laravel apps, you will have a lot of config files so i think you had to specifically alias the config publishing from ```config``` to ```snippets-config``` so that users do not have to guess which package they are publishing if its just ```config```

**Comment by fwartner** [comment]
Well.. This is actually just the tag in order to publish only the config of the package. This has no impact of your application at all. 

Closing this for now.

**Comment by innoflash** [comment]
yes it is sir, i was just thinking it be less confusing when you run the publishing if it has a more direct tag. The tag ```config``` is somehow too generic.

Just what I thought

**Comment by fwartner** [comment]
Merged it. Thanks for your submission. :)
